import type { BrandScaleByTheme } from './themer-bridge';
import type { AppearanceMode } from '../shared/types';

const THEME_CLASS: Record<AppearanceMode, string> = {
  'Light':    'g-root_theme_light',
  'Dark':     'g-root_theme_dark',
  'Light HC': 'g-root_theme_light-hc',
  'Dark HC':  'g-root_theme_dark-hc',
};

function fmtColor(r: number, g: number, b: number, a: number): string {
  const ri = Math.round(r * 255), gi = Math.round(g * 255), bi = Math.round(b * 255);
  if (a >= 0.9999) return `rgb(${ri} ${gi} ${bi})`;
  return `rgb(${ri} ${gi} ${bi} / ${parseFloat(a.toFixed(2))})`;
}

function suffixToVar(suffix: string): string {
  return '--g-color-private-brand-' + suffix.toLowerCase().replace(' solid', '-solid');
}

export function generateBrandCss(brandName: string, scale: BrandScaleByTheme): string {
  const MODES: AppearanceMode[] = ['Light', 'Dark', 'Light HC', 'Dark HC'];
  const blocks: string[] = [
    `/* Brand: ${brandName} — generated by Gravity Brandifyer */`,
    `/* Usage: add the matching class to your app root alongside .g-root */`,
    `/* e.g. <div class="g-root g-root_theme_light g-root_color_light ..."> */`,
    '',
  ];

  for (const mode of MODES) {
    const cls = THEME_CLASS[mode];
    const themeScale = scale[mode];

    // Separate alpha (50–500) and solid (50–1000 Solid) entries, sort each group.
    const alphas = Object.entries(themeScale)
      .filter(([s]) => !s.includes('Solid'))
      .sort(([a], [b]) => parseInt(a) - parseInt(b));

    const solids = Object.entries(themeScale)
      .filter(([s]) => s.includes('Solid'))
      .sort(([a], [b]) => parseInt(a) - parseInt(b));

    const lines: string[] = [`  /* ${mode} */`];

    for (const [suffix, rgba] of alphas) {
      lines.push(`  ${suffixToVar(suffix)}: ${fmtColor(rgba.r, rgba.g, rgba.b, rgba.a)};`);
    }
    // 550 appears as both plain and -solid in the themer reference output
    const s550 = themeScale['550 Solid'];
    if (s550) {
      lines.push(`  --g-color-private-brand-550: ${fmtColor(s550.r, s550.g, s550.b, s550.a)};`);
    }
    for (const [suffix, rgba] of solids) {
      lines.push(`  ${suffixToVar(suffix)}: ${fmtColor(rgba.r, rgba.g, rgba.b, rgba.a)};`);
    }

    blocks.push(`.${cls} {\n${lines.join('\n')}\n}`);
  }

  return blocks.join('\n\n') + '\n';
}
