import { generateFamilyScale } from './themer-bridge';
import type { BrandScaleByTheme } from './themer-bridge';
import type { AppearanceMode, BrandingEntry } from '../shared/types';
import type { ColorFamily } from '../shared/messages';
import { PC_THEMES } from '../shared/constants';

const THEME_CLASS: Record<AppearanceMode, string> = {
  'Light':    'g-root_theme_light',
  'Dark':     'g-root_theme_dark',
  'Light HC': 'g-root_theme_light-hc',
  'Dark HC':  'g-root_theme_dark-hc',
};

function fmtColor(r: number, g: number, b: number, a: number): string {
  const ri = Math.round(r * 255), gi = Math.round(g * 255), bi = Math.round(b * 255);
  if (a >= 0.9999) return `rgb(${ri} ${gi} ${bi})`;
  return `rgb(${ri} ${gi} ${bi} / ${parseFloat(a.toFixed(2))})`;
}

function suffixToCssVar(family: string, suffix: string): string {
  return `--g-color-private-${family}-` + suffix.toLowerCase().replace(' solid', '-solid');
}

function scaleLines(family: string, themeScale: BrandScaleByTheme[AppearanceMode]): string[] {
  const alphas = Object.entries(themeScale)
    .filter(([s]) => !s.includes('Solid'))
    .sort(([a], [b]) => parseInt(a) - parseInt(b));
  const solids = Object.entries(themeScale)
    .filter(([s]) => s.includes('Solid'))
    .sort(([a], [b]) => parseInt(a) - parseInt(b));

  const lines: string[] = [];
  for (const [suffix, rgba] of alphas) {
    lines.push(`  ${suffixToCssVar(family, suffix)}: ${fmtColor(rgba.r, rgba.g, rgba.b, rgba.a)};`);
  }
  // 550 is emitted both as an alpha alias and as a solid — keep parity with themer reference
  const s550 = themeScale['550 Solid'];
  if (s550) {
    lines.push(`  --g-color-private-${family}-550: ${fmtColor(s550.r, s550.g, s550.b, s550.a)};`);
  }
  for (const [suffix, rgba] of solids) {
    lines.push(`  ${suffixToCssVar(family, suffix)}: ${fmtColor(rgba.r, rgba.g, rgba.b, rgba.a)};`);
  }
  return lines;
}

export function generateBrandCss(
  brandName: string,
  brandScale: BrandScaleByTheme,
  colorOverrides: Partial<Record<ColorFamily, string>> = {},
): string {
  const MODES: AppearanceMode[] = ['Light', 'Dark', 'Light HC', 'Dark HC'];

  // Pre-generate family scales for all overrides
  const familyScales: Array<{ family: string; scale: BrandScaleByTheme }> = [];
  for (const [family, hex] of Object.entries(colorOverrides)) {
    if (hex) {
      familyScales.push({ family: family.toLowerCase(), scale: generateFamilyScale(hex, family as ColorFamily) });
    }
  }

  const blocks: string[] = [
    `/* Brand: ${brandName} — generated by Gravity Brandifyer */`,
    '',
  ];

  for (const mode of MODES) {
    const cls = THEME_CLASS[mode];
    const lines: string[] = [`  /* ${mode} */`];

    lines.push(...scaleLines('brand', brandScale[mode]));

    for (const { family, scale } of familyScales) {
      lines.push(`  /* ${family} */`);
      lines.push(...scaleLines(family, scale[mode]));
    }

    blocks.push(`.${cls} {\n${lines.join('\n')}\n}`);
  }

  return blocks.join('\n\n') + '\n';
}

function pcNameToCssValue(pcName: string): string {
  // Always use the last two segments: family + suffix.
  // Works for mono ("Raph/Light/Brand/550 Solid"), service ("[ww] Service/Nirvana/Light/Brand/550 Solid"),
  // and semantic ("[ww] Semantic/Light/Purple/550 Solid") — matches webSyntax() in writer.ts.
  const parts = pcName.split('/');
  const n = parts.length;
  const family = (parts[n - 2] ?? '').toLowerCase();
  const token = (parts[n - 1] ?? '').toLowerCase().replace(/\s+/g, '-');
  return `var(--g-color-private-${family}-${token})`;
}

export function generatePhase2Css(
  brandName: string,
  brandingEntries: BrandingEntry[],
  modes: Array<{ modeId: string; name: string }>,
  embedded = false,
): string {

  const blocks: string[] = [
    `/* Brand: ${brandName} — Branding tokens, generated by Gravity Brandifyer */`,
    ...(embedded ? [] : [`/* Combine with the Phase 1 private colors CSS file */`]),
    '',
  ];

  for (const mode of (['Light', 'Dark', 'Light HC', 'Dark HC'] as AppearanceMode[])) {
    const cls = THEME_CLASS[mode];
    const modeId = modes.find(m => m.name === mode)?.modeId;
    if (!modeId) continue;

    const lines: string[] = [];
    for (const entry of brandingEntries) {
      const pcName = entry.perMode.get(modeId);
      if (!pcName) continue;
      const cssVar = `--g-color-${entry.suffix.toLowerCase().replace(/\s+/g, '-')}`;
      lines.push(`  ${cssVar}: ${pcNameToCssValue(pcName)};`);
    }
    if (lines.length === 0) continue;

    blocks.push(`.${cls} {\n${lines.join('\n')}\n}`);
  }

  return blocks.join('\n\n') + '\n';
}
