import { generateFamilyScale } from './themer-bridge';
import type { BrandScaleByTheme } from './themer-bridge';
import type { AppearanceMode } from '../shared/types';
import type { ColorFamily } from '../shared/messages';

const THEME_CLASS: Record<AppearanceMode, string> = {
  'Light':    'g-root_theme_light',
  'Dark':     'g-root_theme_dark',
  'Light HC': 'g-root_theme_light-hc',
  'Dark HC':  'g-root_theme_dark-hc',
};

function fmtColor(r: number, g: number, b: number, a: number): string {
  const ri = Math.round(r * 255), gi = Math.round(g * 255), bi = Math.round(b * 255);
  if (a >= 0.9999) return `rgb(${ri} ${gi} ${bi})`;
  return `rgb(${ri} ${gi} ${bi} / ${parseFloat(a.toFixed(2))})`;
}

function suffixToCssVar(family: string, suffix: string): string {
  return `--g-color-private-${family}-` + suffix.toLowerCase().replace(' solid', '-solid');
}

function scaleLines(family: string, themeScale: BrandScaleByTheme[AppearanceMode]): string[] {
  const alphas = Object.entries(themeScale)
    .filter(([s]) => !s.includes('Solid'))
    .sort(([a], [b]) => parseInt(a) - parseInt(b));
  const solids = Object.entries(themeScale)
    .filter(([s]) => s.includes('Solid'))
    .sort(([a], [b]) => parseInt(a) - parseInt(b));

  const lines: string[] = [];
  for (const [suffix, rgba] of alphas) {
    lines.push(`  ${suffixToCssVar(family, suffix)}: ${fmtColor(rgba.r, rgba.g, rgba.b, rgba.a)};`);
  }
  // 550 is emitted both as an alpha alias and as a solid — keep parity with themer reference
  const s550 = themeScale['550 Solid'];
  if (s550) {
    lines.push(`  --g-color-private-${family}-550: ${fmtColor(s550.r, s550.g, s550.b, s550.a)};`);
  }
  for (const [suffix, rgba] of solids) {
    lines.push(`  ${suffixToCssVar(family, suffix)}: ${fmtColor(rgba.r, rgba.g, rgba.b, rgba.a)};`);
  }
  return lines;
}

export function generateBrandCss(
  brandName: string,
  brandScale: BrandScaleByTheme,
  colorOverrides: Partial<Record<ColorFamily, string>> = {},
): string {
  const MODES: AppearanceMode[] = ['Light', 'Dark', 'Light HC', 'Dark HC'];

  // Pre-generate family scales for all overrides
  const familyScales: Array<{ family: string; scale: BrandScaleByTheme }> = [];
  for (const [family, hex] of Object.entries(colorOverrides)) {
    if (hex) {
      familyScales.push({ family: family.toLowerCase(), scale: generateFamilyScale(hex, family as ColorFamily) });
    }
  }

  const blocks: string[] = [
    `/* Brand: ${brandName} — generated by Gravity Brandifyer */`,
    `/* Usage: add the matching class to your app root alongside .g-root */`,
    `/* e.g. <div class="g-root g-root_theme_light g-root_color_light ..."> */`,
    '',
  ];

  for (const mode of MODES) {
    const cls = THEME_CLASS[mode];
    const lines: string[] = [`  /* ${mode} */`];

    lines.push(...scaleLines('brand', brandScale[mode]));

    for (const { family, scale } of familyScales) {
      lines.push(`  /* ${family} */`);
      lines.push(...scaleLines(family, scale[mode]));
    }

    blocks.push(`.${cls} {\n${lines.join('\n')}\n}`);
  }

  return blocks.join('\n\n') + '\n';
}
